info:
  title: URL Shorter API
  version: v1.0.0

app:
  base-url: http://localhost:8080
  shorten-path-prefix: /shorten

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        snowflake.id.generation.time: true

snowflake:
  worker-thread-count: 4
