spring:
  r2dbc:
    pool:
      initial-size: 10
      max-size: 10
      max-life-time: 30m
      max-idle-time: 30m

---
spring:
  config:
    activate:
      on-profile: infra
  r2dbc:
    url: r2dbc:mariadb://127.0.0.1:3306/mydatabase?allowPublicKeyRetrieval=true
    username: app_rw
    password: app_rw
  sql:
    init:
      mode: never