info:
  title: GLOBAL TRANSACTION ID API
  version: v1.0.0

app:
  base-url: http://localhost:8081

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        snowflake.id.generation.time: true

snowflake:
  worker-thread-count: 4
